"""
Module: knowledge/schemas/ba_profile.py
Role: Schema for Business Analyst Profiles — the intelligence layer
      that transforms raw Knowledge Graphs into actionable business advice.
      One BA Profile per functional domain (not per module).
Dependencies: pydantic
"""

from pydantic import BaseModel


class FeatureDiscovery(BaseModel, frozen=True):
    """A feature the client might not know about."""

    name: str  # Human-readable name
    module: str  # Odoo module
    model: str  # Odoo model
    field_or_setting: str  # Specific field/config to activate
    description: str  # What it does in business terms
    business_value: str  # Why it matters for the PME
    how_to_activate: str  # Steps to enable (plain language)
    prerequisites: list[str] = []  # Required modules/config
    complexity: str = "simple"  # simple, medium, complex


class DomainCapability(BaseModel, frozen=True):
    """What a functional domain can do."""

    name: str  # e.g. "Gestion des devis"
    description: str  # Business description
    key_models: list[str]  # Involved Odoo models
    common_workflows: list[str]  # Typical business processes


class Gotcha(BaseModel, frozen=True):
    """Pitfall or constraint extracted from the code."""

    description: str
    source_model: str  # Which model has this constraint
    source_constraint: str  # Constraint name or type
    workaround: str = ""  # How to avoid the issue


class BAProfile(BaseModel, frozen=True):
    """
    Business Analyst Profile for a functional domain.

    Generated by the BA Factory from Knowledge Graphs.
    Used by the Orchestrator to answer business questions.
    """

    domain_name: str  # e.g. "Sales & CRM"
    domain_id: str  # e.g. "sales_crm"
    modules_covered: list[str]  # e.g. ["sale", "crm", "sale_management"]
    language: str = "fr"  # Output language

    # Business intelligence
    summary: str  # 2-3 sentence overview of the domain
    capabilities: list[DomainCapability] = []  # What the domain can do
    feature_discoveries: list[FeatureDiscovery] = []  # Hidden gems to reveal
    gotchas: list[Gotcha] = []  # Pitfalls and constraints

    # Cross-module intelligence
    cross_module_combos: list[str] = []  # e.g. "sale + stock = auto-delivery"
    limitations: list[str] = []  # What requires custom dev

    # Metadata
    odoo_version: str = ""
    generated_at: str = ""  # ISO datetime
    model_used: str = ""  # LLM model that generated this
    token_count: int = 0  # Tokens used for generation
