"""
Module: knowledge/schemas/ba_profile.py
Role: Schema for Business Analyst Profiles — the intelligence layer
      that transforms raw Knowledge Graphs into actionable business advice.
      One BA Profile per functional domain (not per module).
Dependencies: pydantic
"""

from pydantic import BaseModel


class FeatureDiscovery(BaseModel, frozen=True):
    """A feature the client might not know about."""

    name: str  # Human-readable name
    module: str  # Odoo module
    model: str  # Odoo model
    field_or_setting: str  # Specific field/config to activate
    description: str  # What it does in business terms
    business_value: str  # Why it matters for the PME
    how_to_activate: str  # Steps to enable (plain language)
    prerequisites: list[str] = []  # Required modules/config
    complexity: str = "simple"  # simple, medium, complex


class DomainCapability(BaseModel, frozen=True):
    """What a functional domain can do."""

    name: str  # e.g. "Gestion des devis"
    description: str  # Business description
    key_models: list[str]  # Involved Odoo models
    common_workflows: list[str]  # Typical business processes


class Gotcha(BaseModel, frozen=True):
    """Pitfall or constraint extracted from the code."""

    description: str
    source_model: str  # Which model has this constraint
    source_constraint: str  # Constraint name or type
    workaround: str = ""  # How to avoid the issue


class Workflow(BaseModel, frozen=True):
    """A business workflow with steps and models involved."""

    name: str  # e.g. "Cycle de vente"
    description: str  # Business explanation
    steps: list[str] = []  # Ordered steps
    models_involved: list[str] = []  # Odoo models in this workflow
    key_fields_per_step: dict[str, list[str]] = {}  # model → [fields]


class QAPair(BaseModel, frozen=True):
    """A typical question with the exact Odoo query to answer it."""

    question: str  # e.g. "Combien de commandes en retard ?"
    answer: str  # Direct answer template
    models_to_query: list[str] = []  # Which models to search
    fields_to_fetch: list[str] = []  # Which fields to return
    domain_filter_example: str = ""  # e.g. "[('state','=','draft')]"


class RecommendedConfig(BaseModel, frozen=True):
    """Configuration recommendations by company size."""

    small_company: str = ""  # < 20 employees
    medium_company: str = ""  # 20-100 employees
    large_company: str = ""  # > 100 employees


class BAProfile(BaseModel, frozen=True):
    """
    Business Analyst Profile for a functional domain.

    Generated by the BA Factory from Knowledge Graphs.
    Used by the Orchestrator to answer business questions.
    """

    domain_name: str
    domain_id: str
    modules_covered: list[str]
    language: str = "fr"

    # Business intelligence
    summary: str
    workflows: list[Workflow] = []  # How things flow
    capabilities: list[DomainCapability] = []
    feature_discoveries: list[FeatureDiscovery] = []
    qa_pairs: list[QAPair] = []  # Q&A with exact Odoo queries
    gotchas: list[Gotcha] = []
    recommended_config: RecommendedConfig | None = None

    # Cross-module intelligence
    cross_module_combos: list[str] = []
    limitations: list[str] = []

    # Metadata
    odoo_version: str = ""
    generated_at: str = ""
    model_used: str = ""
    token_count: int = 0
